import React from 'react'
import './collections.css'

const collectionsList = [
  {
    id:1,
    title:"trending this week",
    cover:"data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwkHBgoJCAkLCwoMDxkQDw4ODx4WFxIZJCAmJSMgIyIoLTkwKCo2KyIjMkQyNjs9QEBAJjBGS0U+Sjk/QD3/2wBDAQsLCw8NDx0QEB09KSMpPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT3/wAARCAAyADIDASIAAhEBAxEB/8QAGwABAAIDAQEAAAAAAAAAAAAAAAIEAQMHBQb/xAApEAABAwEIAAYDAAAAAAAAAAAAAQIDBAUGERITFFKRFSFCUVNxFjFh/8QAGAEBAAMBAAAAAAAAAAAAAAAAAAIDBAH/xAAaEQEBAQEBAQEAAAAAAAAAAAAAAQIRAxNB/9oADAMBAAIRAxEAPwDswIajE9SDUZyQCYIarOSDUZyQCYI52+5nMnuBkEcye4A49LfardEj2vVMTEN8a+VcrXKqlJ91q1KdGJG7FP4bLMu7WwS4viXozauut9nnfKT9XvyW0Wuxc9cCy+9VVGxrkkVTVU2NUvZlSJcforJdusyoiscUa+t1LKjjPnJXt0t7pWxZ5n+Rll/Wvly5vI+ctGwa/QyRxuPLbd+0Gxqmi7N9Gy3WYpuM3PXRUvY1Ux1E7BzfwO2ODwS7VPHfNrEvoTobSHgnRuBLjjTtYuCdDbRcENwA0LSQu/bE6MbGD429FgAV9jB8begWAAAAAAAAAAAAH//Z",
    places:"12 places"
  },
  {
    id:2,
    title:"Collections",
    cover:"data:image/jpg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/2wBDAAsHCAkIBwsJCQkMCwsNEBoREA8PECAXGBMaJiIoKCYiJSQqMD0zKi05LiQlNUg1OT9BREVEKTNLUEpCTz1DREH/2wBDAQsMDBAOEB8RER9BLCUsQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUH/wAARCAAyADIDASIAAhEBAxEB/8QAGwABAAIDAQEAAAAAAAAAAAAAAAIDAQQFBwb/xAApEAACAgECBQMEAwAAAAAAAAAAAQIDBBESBQYxUVITIZEUFSIjQUJT/8QAGAEBAQEBAQAAAAAAAAAAAAAAAAQCAwH/xAAcEQEAAgIDAQAAAAAAAAAAAAAAARECIgMSIRP/2gAMAwEAAhEDEQA/APXANV3Mbl3AyCO+PkjO+PdAZBjfHuhvj3QGQR9SHkgBxb+JSqrc2+h81l83XTudVWvXQ7d+HbbBxcXozjWctzqsdkIatnHPtWrpjV+p4nEs6z8pSaRuTzsnZrvOdLHzq47Y1v4FeNm2Q2uLWpFfLfqmI46Xy45bH2dhG/mCyFTas9zQyOCZbbaizSu4LmNabZGo+jyei980ZWr/AGA5/wBiy/8AOQNbs6vX9kewdcX/AAiQL0qt0VvrBBY9S6RRYAIejX4oi8ap/wBF8FoFCn6WnwXwC4AAAAAAAAAAAB//2Q==",
    places:"12 places"
  },
  {
    id:3,
    title:"Collections",
    cover:"",
    places:"12 places"
  }
]
const Collections = () => {
  return (
    <div>
      <Collections/>
    </div>
  )
}

export default Collections;

